/* Certification Compass — data and shared helpers. Edit CERTS to add or update certifications. */
var PEG = 3.6725;

var ROLES = [
  {k:"fe", label:"Frontend engineer"},
  {k:"be", label:"Backend engineer"},
  {k:"fs", label:"Full stack engineer"},
  {k:"mn", label:"Mobile engineer (native iOS / Android)"},
  {k:"mh", label:"Mobile engineer (hybrid: Flutter / React Native)"},
  {k:"dba", label:"Database administrator"},
  {k:"dev", label:"DevOps engineer"},
  {k:"sre", label:"SRE / Platform engineer"},
  {k:"de", label:"Data engineer"},
  {k:"ds", label:"Data scientist / ML engineer"},
  {k:"ai", label:"AI engineer (LLMs, agents, RAG)"},
  {k:"sec", label:"Security engineer"},
  {k:"qa", label:"QA / Test automation engineer"},
  {k:"tpm", label:"Technical product manager"},
  {k:"sa", label:"Solution architect"},
  {k:"ea", label:"Enterprise architect"},
  {k:"em", label:"Engineering manager / Head of engineering"},
  {k:"cto", label:"CTO / VP Engineering"}
];

var LEVELS = [
  {short:"Fresher", yrs:"0–1 yr", name:"Fresher"},
  {short:"Junior", yrs:"1–3 yrs", name:"Junior"},
  {short:"Mid", yrs:"3–5 yrs", name:"Mid-level"},
  {short:"Senior", yrs:"5–8 yrs", name:"Senior"},
  {short:"Staff / Lead", yrs:"8–12 yrs", name:"Staff / Lead"},
  {short:"Principal", yrs:"12+ yrs", name:"Principal / Architect"},
  {short:"Director / CTO", yrs:"exec", name:"Director / CTO"}
];

var ROLE_ADVICE = {
  fe:"Dubai hiring for frontend is portfolio-first. One cloud fundamentals exam plus a deployed project beats a stack of course badges; accessibility skills are a quiet differentiator for UAE government work.",
  be:"AWS Solutions Architect Associate or an Azure associate exam is the single most useful credential. Add Kubernetes, Terraform or Kafka as you grow.",
  fs:"A cloud associate exam (AWS SAA or Azure) is the strongest signal; add an AI app exam if you build LLM features.",
  mn:"No vendor certification moves the needle for native mobile — shipped App Store / Play Store apps do. Use certs only to branch into cloud or backend.",
  mh:"Flutter and React Native have no official certification that hiring managers filter on. Ship apps; use cloud certs to broaden.",
  dba:"Pair a database vendor cert with a cloud data cert. Oracle and SQL Server still run core banking and government systems in the UAE.",
  dev:"CKA + Terraform + one cloud professional exam is the strongest DevOps trio in UAE job ads.",
  sre:"CKA is the anchor; Google's DevOps exam is the most SRE-specific. Reliability track records matter more than any badge.",
  de:"One cloud data exam (AWS DEA, Microsoft Fabric DP-700 or Databricks) plus pipelines you can show. Fabric adoption is fast in UAE enterprises.",
  ds:"Certs are secondary to Kaggle-style work and shipped models. One cloud ML exam helps get past HR filters in banks and government.",
  ai:"Pick one hyperscaler AI exam — Azure is strongest in UAE government via Microsoft, G42 and Core42 — and back it with shipped agents and RAG systems.",
  sec:"Security is the most certification-driven track in the UAE. Regulated employers often require CISSP or CISM, and ISO 27001 for DESC ISR and UAE IA work.",
  qa:"ISTQB Foundation is the one QA cert UAE hiring managers and government tenders actually filter on.",
  tpm:"Scrum product-owner credentials and PMP carry weight in UAE government and banking; AI literacy exams are now expected.",
  sa:"A cloud architect exam (AWS SAA → SAP, or Azure AZ-305) is expected; TOGAF becomes important for government and enterprise clients.",
  ea:"TOGAF is close to mandatory for EA roles in UAE government transformation programmes; add security and AI governance.",
  em:"Certs matter little for promotion; Scrum, PMP and AI-governance literacy help in UAE corporates and government entities.",
  cto:"At CTO level certifications rarely matter — outcomes do. Governance literacy (AI, security, privacy) is what regulators and boards ask about."
};

var LEVEL_ADVICE = [
  "One fundamentals exam plus a free credential, then build projects. Skip expensive bootcamp bundles.",
  "Your first associate-level cloud exam has the highest return now.",
  "Go hands-on and specialise: Kubernetes, infrastructure as code, data platforms or AI.",
  "Professional-level exams plus one cross-skill — security or architecture.",
  "Certs now signal breadth: architecture, security, governance.",
  "Frameworks and governance (TOGAF, CISSP, ISO 42001) matter more than tool exams.",
  "Optional. Employers judge outcomes; governance literacy beats tool exams."
];

var DOMS = [
  {k:"gov", label:"Government & semi-government", regs:["DESC ISR (Dubai)","UAE IA Standard · Cybersecurity Council","Dubai Digital Authority","TDRA"], text:"Dubai government entities and their suppliers must comply with the DESC Information Security Regulation; federal critical-infrastructure entities follow the UAE Information Assurance standard. Tenders frequently ask for ISO 27001, ITIL, TOGAF, PMP and ISTQB-certified staff. Microsoft and Oracle dominate the stack."},
  {k:"fin", label:"Banking, fintech & virtual assets", regs:["CBUAE","DFSA · DIFC","FSRA · ADGM","VARA"], text:"Banks and payment firms fall under Central Bank of the UAE cyber guidelines; DIFC firms under DFSA technology-risk rules; crypto firms under VARA. Audit-facing roles value CISA, CRISC and CISM; architects need cloud security depth for outsourcing approvals."},
  {k:"health", label:"Healthcare", regs:["ADHICS · DoH Abu Dhabi","DHA · NABIDH","Malaffi","Health Data Law 2019"], text:"Abu Dhabi providers and insurers must meet ADHICS; Dubai and Abu Dhabi run health-information exchanges (NABIDH, Malaffi) built on HL7/FHIR. The federal health data law adds localisation rules, so privacy and interoperability skills are both in demand."},
  {k:"energy", label:"Energy & critical infrastructure", regs:["UAE IA Standard","ADNOC / DEWA / ENEC supply chain","NCEMA 7000"], text:"Oil, gas, utilities and nuclear operators run operational-technology networks where IT certs alone fall short. OT security (IEC 62443, GICSP) and business continuity aligned with the UAE's NCEMA 7000 standard are the differentiators."},
  {k:"ai", label:"AI & AI governance", regs:["UAE AI Strategy 2031","Federal Authority for AI & Data (2026)","AI-agent mandate 2028"], text:"In 2026 the UAE directed that half of federal government services move to autonomous AI agents by 2028 and created a federal AI and data authority. Builders need hands-on agent / RAG credentials; leaders need AI-governance standards such as ISO 42001 and IAPP AIGP."},
  {k:"privacy", label:"Data privacy", regs:["UAE PDPL (Decree-Law 45/2021)","DIFC Data Protection Law","ADGM Data Protection Regs"], text:"The federal PDPL and the DIFC and ADGM free-zone laws are all modelled on GDPR, so European privacy credentials transfer directly. Privacy-by-design skills are increasingly expected from backend and data engineers, not only from DPOs."},
  {k:"cloud", label:"Sovereign cloud & data residency", regs:["Azure UAE North / Central (Core42)","AWS me-central-1","Oracle Dubai & Abu Dhabi","Google Cloud: no UAE region"], text:"Data-residency rules push government, health and finance workloads onto in-country regions. Azure (with Core42 sovereign cloud), AWS and Oracle all run UAE regions; Google Cloud's nearest are Doha and Dammam, which is why GCP certs rate lower here."},
  {k:"free", label:"Free & UAE programmes", regs:["Dubai Future Foundation","Dubai Centre for AI","Vendor free tiers"], text:"Free credentials worth your time — including Dubai government initiatives open to residents and global learners, and free vendor programmes that still show up well on a CV."}
];

var CATS = ["All","Cloud","AI","Security","Data","DevOps & platform","Architecture","QA","Product & delivery","Governance & privacy","Dev & mobile"];

var CERTS = [
/* ---------- AWS ---------- */
{id:"clf", n:"AWS Certified Cloud Practitioner", p:"AWS", code:"CLF-C02", usd:100, url:"https://aws.amazon.com/certification/certified-cloud-practitioner/", r:6, lv:[0,2], m:[], s:["tpm","qa","fe","mn","mh"], c:["be","fs","dba","ds","em"], x:["dev","sre","sa","ea","cto"], why:"Entry-level cloud literacy. Good first exam for non-cloud roles; engineers aiming at cloud should go straight to an associate exam.", uae:"AWS has had a UAE region since 2022; common ask in Dubai job posts for juniors.", tags:[], cat:"Cloud", dom:["cloud"]},
{id:"aif", n:"AWS Certified AI Practitioner", p:"AWS", code:"AIF-C01", usd:100, url:"https://aws.amazon.com/certification/certified-ai-practitioner/", r:7, lv:[0,5], m:[], s:["tpm","em","qa"], c:["fe","be","fs","mn","mh","ds","de","sa","cto"], x:["ai"], why:"GenAI and ML literacy for non-specialists. AI engineers will outgrow it quickly — take the GenAI Developer Professional instead.", uae:"Matches the UAE push for AI fluency in every role.", tags:[], cat:"AI", dom:["ai"]},
{id:"saa", n:"AWS Certified Solutions Architect – Associate", p:"AWS", code:"SAA-C03", usd:150, url:"https://aws.amazon.com/certification/certified-solutions-architect-associate/", r:9, lv:[1,4], m:["sa","fs","be","dev","sre"], s:["de","ai","dba","sec","em","fe","tpm"], c:["mn","mh","ds","ea","qa"], x:[], why:"The most-requested cloud certification in UAE job ads; proves you can design resilient, cost-aware systems on AWS.", uae:"Consistently top of Dubai and Abu Dhabi cloud job filters.", tags:[], cat:"Cloud", dom:["cloud","fin"]},
{id:"dva", n:"AWS Certified Developer – Associate", p:"AWS", code:"DVA-C02", usd:150, url:"https://aws.amazon.com/certification/certified-developer-associate/", r:7, lv:[1,3], m:[], s:["be","fs"], c:["fe","mn","mh","qa"], x:["sa"], why:"Serverless, SDKs, CI/CD and debugging on AWS. Architects get more from SAA.", uae:"Useful for product companies and startups building on AWS.", tags:[], cat:"Cloud", dom:[]},
{id:"soa", n:"AWS Certified CloudOps Engineer – Associate", p:"AWS", code:"SOA-C03", usd:150, url:"https://aws.amazon.com/certification/certified-cloudops-engineer-associate/", r:7, lv:[1,4], m:[], s:["sre","dev"], c:["dba","sec"], x:[], why:"Monitoring, automation, networking and incident handling on AWS (formerly SysOps Administrator).", uae:"Managed-service providers in Dubai hire against it.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"dea", n:"AWS Certified Data Engineer – Associate", p:"AWS", code:"DEA-C01", usd:150, url:"https://aws.amazon.com/certification/certified-data-engineer-associate/", r:8, lv:[1,4], m:["de"], s:["ds","dba"], c:["ai","be"], x:[], why:"Pipelines, Glue, Redshift, streaming and governance — the AWS data-engineering baseline.", uae:"Data platform teams in UAE banks and telcos list it often.", tags:[], cat:"Data", dom:[]},
{id:"mla", n:"AWS Certified Machine Learning Engineer – Associate", p:"AWS", code:"MLA-C01", usd:150, url:"https://aws.amazon.com/certification/certified-machine-learning-engineer-associate/", r:8, lv:[1,4], m:[], s:["ds","ai"], c:["de"], x:[], why:"SageMaker, feature pipelines, model deployment and MLOps. Replaces the retired ML Specialty.", uae:"Good fit for ML teams in AWS-first UAE companies.", tags:[], cat:"AI", dom:["ai"]},
{id:"sap", n:"AWS Certified Solutions Architect – Professional", p:"AWS", code:"SAP-C02", usd:300, url:"https://aws.amazon.com/certification/certified-solutions-architect-professional/", r:9, lv:[3,6], m:["sa"], s:["ea","dev","em"], c:["fs","be","sre","de","ai","cto","sec"], x:[], why:"The senior architecture signal: multi-account, migration, hybrid and cost at scale.", uae:"Heavily valued by UAE consultancies, system integrators and AWS partners.", tags:[], cat:"Architecture", dom:["cloud","fin"]},
{id:"dop", n:"AWS Certified DevOps Engineer – Professional", p:"AWS", code:"DOP-C02", usd:300, url:"https://aws.amazon.com/certification/certified-devops-engineer-professional/", r:8, lv:[3,5], m:["dev"], s:["sre"], c:["sa","fs","be"], x:[], why:"CI/CD, infrastructure as code, observability and resilience at professional depth.", uae:"Senior DevOps roles in Dubai often list it alongside CKA.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"aip", n:"AWS Certified Generative AI Developer – Professional", p:"AWS", code:"AIP-C01", usd:300, url:"https://aws.amazon.com/certification/certified-generative-ai-developer-professional/", r:8, lv:[2,5], m:[], s:["ai","sa","fs","be"], c:["ds","de","cto"], x:[], why:"Bedrock, RAG, agents, guardrails and evaluation — the most complete GenAI build exam from a hyperscaler.", uae:"Fits the UAE's AI-agent rollout in government and banking.", tags:["new"], cat:"AI", dom:["ai"]},
{id:"scs", n:"AWS Certified Security – Specialty", p:"AWS", code:"SCS-C03", usd:300, url:"https://aws.amazon.com/certification/certified-security-specialty/", r:8, lv:[2,5], m:[], s:["sec","sre","dev"], c:["sa","ea"], x:[], why:"IAM, KMS, detection, incident response and data protection natively on AWS.", uae:"Helps with CBUAE outsourcing and DESC cloud-security reviews.", tags:[], cat:"Security", dom:["fin","gov"]},
{id:"mls", n:"AWS Certified Machine Learning – Specialty", p:"AWS", code:"MLS-C01", usd:null, note:"Retired", url:"https://aws.amazon.com/certification/", r:2, lv:[0,6], m:[], s:[], c:[], x:["ds","ai"], why:"Retired 31 March 2026. Take ML Engineer Associate or GenAI Developer Professional instead.", uae:"Old holders keep the title, but don't prepare for it now.", tags:["retired"], cat:"AI", dom:[]},
{id:"ans", n:"AWS Certified Advanced Networking – Specialty", p:"AWS", code:"ANS-C01", usd:null, note:"Retired", url:"https://aws.amazon.com/certification/", r:2, lv:[0,6], m:[], s:[], c:[], x:["dev","sre","sa"], why:"Last exam date was 25 August 2026. Networking depth is now covered in SAP-C02 and CloudOps.", uae:"Not bookable any more.", tags:["retired"], cat:"Cloud", dom:[]},

/* ---------- Microsoft ---------- */
{id:"az900", n:"Microsoft Azure Fundamentals", p:"Microsoft", code:"AZ-900", usd:99, aed:365, url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/", r:6, lv:[0,2], m:[], s:["tpm","qa","fe","mn","mh","em"], c:["be","fs","dba","ds"], x:["dev","sre","sa","ea","cto"], why:"Azure basics in a weekend. Quick win for juniors and non-engineers; free vouchers often come via Microsoft Virtual Training Days.", uae:"Azure runs UAE North / Central regions and Microsoft is the dominant stack in UAE government.", tags:[], cat:"Cloud", dom:["cloud","gov"]},
{id:"ai901", n:"Microsoft Azure AI Fundamentals", p:"Microsoft", code:"AI-901", usd:99, aed:365, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=AI-901", r:7, lv:[0,4], m:[], s:["tpm","em","qa"], c:["fe","be","fs","mn","mh","ds","sa","de"], x:["ai"], why:"New 2026 replacement for AI-900: AI workloads, responsible AI, agents and Azure AI services at concept level.", uae:"Cheap AI-literacy proof aligned with the UAE government's AI push.", tags:["new"], cat:"AI", dom:["ai"]},
{id:"az104", n:"Microsoft Azure Administrator Associate", p:"Microsoft", code:"AZ-104", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-administrator/", r:8, lv:[1,4], m:[], s:["dev","sre","sa"], c:["be","fs","dba","sec"], x:[], why:"Hands-on Azure identity, networking, storage and compute. Prerequisite for the Solutions Architect Expert.", uae:"Most requested Azure cert for UAE government IT and system integrators.", tags:[], cat:"Cloud", dom:["cloud","gov"]},
{id:"az305", n:"Microsoft Azure Solutions Architect Expert", p:"Microsoft", code:"AZ-305", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-solutions-architect/", r:9, lv:[3,6], m:["sa"], s:["ea","em","dev"], c:["fs","be","sre","de","cto","sec"], x:[], why:"Design identity, data, business continuity and infrastructure on Azure. Requires AZ-104.", uae:"Big in UAE government, banks and Microsoft partners — arguably the top architect cert locally.", tags:[], cat:"Architecture", dom:["cloud","gov","fin"]},
{id:"az400", n:"Microsoft DevOps Engineer Expert", p:"Microsoft", code:"AZ-400", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/devops-engineer/", r:8, lv:[2,5], m:[], s:["dev","sre"], c:["be","fs","qa"], x:[], why:"Azure DevOps and GitHub pipelines, release strategy, security and observability. Requires AZ-104 or the AI-200 developer exam.", uae:"Standard in Microsoft-centric UAE enterprises.", tags:[], cat:"DevOps & platform", dom:["gov"]},
{id:"ai200", n:"Microsoft Azure AI Cloud Developer", p:"Microsoft", code:"AI-200", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=AI-200", r:7, lv:[1,4], m:[], s:["be","fs"], c:["fe","ai"], x:[], why:"Azure application development for the AI era; successor to AZ-204.", uae:"Fits teams building on Azure UAE regions.", tags:["new"], cat:"Cloud", dom:[]},
{id:"ai103", n:"Microsoft Azure AI App & Agent Developer", p:"Microsoft", code:"AI-103", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=AI-103", r:8, lv:[2,5], m:["ai"], s:["fs","be"], c:["sa","ds"], x:[], why:"Microsoft Foundry, agents, RAG and evaluation on Azure; replaces AI-102. The Azure counterpart to AWS AIP-C01.", uae:"Most relevant AI build exam locally, given Microsoft's partnership with G42 / Core42 and government Azure adoption.", tags:["new"], cat:"AI", dom:["ai","gov"]},
{id:"ai300", n:"Microsoft Machine Learning Operations Engineer", p:"Microsoft", code:"AI-300", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=AI-300", r:7, lv:[2,5], m:[], s:["ds"], c:["ai","de"], x:[], why:"Model training, deployment and MLOps on Azure; replaces DP-100 Data Scientist.", uae:"For ML teams in Azure-first banks and government entities.", tags:["new"], cat:"AI", dom:["ai"]},
{id:"dp700", n:"Microsoft Fabric Data Engineer Associate", p:"Microsoft", code:"DP-700", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/fabric-data-engineer-associate/", r:8, lv:[1,4], m:[], s:["de"], c:["dba","ds"], x:[], why:"Lakehouse, warehouse and real-time pipelines in Microsoft Fabric.", uae:"Fabric adoption is fast in UAE government and enterprise data programmes.", tags:[], cat:"Data", dom:["gov"]},
{id:"pl300", n:"Microsoft Power BI Data Analyst", p:"Microsoft", code:"PL-300", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/data-analyst-associate/", r:7, lv:[0,4], m:[], s:["ds"], c:["de","tpm","dba"], x:[], why:"Data modelling, DAX and reporting. Very practical for analytics-heavy roles.", uae:"Power BI is the default BI tool across UAE government and enterprise.", tags:[], cat:"Data", dom:["gov"]},
{id:"dp300", n:"Microsoft Azure Database Administrator", p:"Microsoft", code:"DP-300", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-database-administrator-associate/", r:7, lv:[1,4], m:[], s:["dba"], c:["de"], x:[], why:"SQL Server and Azure SQL operations, HA/DR, performance and security.", uae:"SQL Server estates are everywhere in UAE government and mid-size enterprises.", tags:[], cat:"Data", dom:["gov"]},
{id:"dp800", n:"Microsoft SQL AI Developer", p:"Microsoft", code:"DP-800", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=DP-800", r:6, lv:[1,4], m:[], s:[], c:["dba","be","de"], x:[], why:"New 2026 exam on vector search and AI features inside SQL Server / Azure SQL.", uae:"Early-adopter signal; demand still forming.", tags:["new"], cat:"Data", dom:[]},
{id:"sc500", n:"Microsoft Cloud & AI Security Engineer", p:"Microsoft", code:"SC-500", usd:165, aed:600, url:"https://learn.microsoft.com/en-us/credentials/browse/?terms=SC-500", r:8, lv:[2,5], m:[], s:["sec"], c:["sre","dev","sa"], x:[], why:"Securing Azure and AI workloads; replaces AZ-500.", uae:"Relevant to DESC ISR and UAE IA controls on Azure.", tags:["new"], cat:"Security", dom:["gov","fin"]},
{id:"az204", n:"Microsoft Azure Developer Associate", p:"Microsoft", code:"AZ-204", usd:null, note:"Retiring", url:"https://learn.microsoft.com/en-us/credentials/certifications/azure-developer/", r:3, lv:[0,6], m:[], s:[], c:[], x:["be","fs"], why:"Being replaced by AI-200 in 2026 — don't start fresh preparation on it.", uae:"Existing holders stay certified until renewal lapses.", tags:["retiring"], cat:"Cloud", dom:[]},
{id:"appskills", n:"Microsoft Applied Skills", p:"Microsoft", code:"Lab-based", usd:0, url:"https://learn.microsoft.com/en-us/credentials/applied-skills/", r:6, lv:[0,4], m:[], s:[], c:["fe","be","fs","dev","ds","ai","de","dba","qa"], x:[], why:"Free, hands-on lab assessments (RAG apps, Fabric, containers, security). Great CV fillers that prove real tasks.", uae:"Shows up well with Microsoft-centric UAE employers at zero cost.", tags:["free"], cat:"Cloud", dom:["free"]},
{id:"ghf", n:"GitHub Foundations", p:"GitHub", code:"GH-900", usd:99, url:"https://learn.microsoft.com/en-us/credentials/certifications/github-foundations/", r:5, lv:[0,1], m:[], s:[], c:["fe","be","fs","mn","mh","qa"], x:[], why:"Git and GitHub basics; free for students through GitHub Education.", uae:"Low hiring weight — a public GitHub profile matters more.", tags:[], cat:"Dev & mobile", dom:[]},
{id:"ghact", n:"GitHub Actions", p:"GitHub", code:"GH-200", usd:99, url:"https://learn.microsoft.com/en-us/credentials/certifications/github-actions/", r:6, lv:[1,4], m:[], s:[], c:["dev","sre","be","fs"], x:[], why:"Workflow authoring, reusable actions, secrets and runners.", uae:"Handy where GitHub Enterprise is the CI standard.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"ghcop", n:"GitHub Copilot", p:"GitHub", code:"GH-300", usd:99, url:"https://learn.microsoft.com/en-us/credentials/certifications/github-copilot/", r:5, lv:[1,4], m:[], s:[], c:["fe","be","fs","em"], x:[], why:"Proves an AI-assisted development workflow. Nice to have, never a hiring filter.", uae:"Low local demand.", tags:[], cat:"Dev & mobile", dom:[]},

/* ---------- Google Cloud ---------- */
{id:"cdl", n:"Google Cloud Digital Leader", p:"Google Cloud", code:"CDL", usd:99, url:"https://cloud.google.com/learn/certification/cloud-digital-leader", r:5, lv:[0,2], m:[], s:[], c:["tpm","em"], x:["dev","sre","sa"], why:"Business-level cloud concepts. Engineers should skip to Associate Cloud Engineer.", uae:"No GCP region in the UAE, so local demand is modest.", tags:[], cat:"Cloud", dom:[]},
{id:"gail", n:"Google Cloud Generative AI Leader", p:"Google Cloud", code:"GAIL", usd:99, url:"https://cloud.google.com/learn/certification/generative-ai-leader", r:7, lv:[2,6], m:[], s:["tpm","em","cto"], c:["ea","sa"], x:[], why:"GenAI strategy, use-case selection and responsible AI for leaders — vendor-light enough to be useful anywhere.", uae:"Good fit for leaders driving AI-agent programmes.", tags:[], cat:"AI", dom:["ai"]},
{id:"ace", n:"Google Associate Cloud Engineer", p:"Google Cloud", code:"ACE", usd:125, url:"https://cloud.google.com/learn/certification/cloud-engineer", r:7, lv:[1,4], m:[], s:[], c:["dev","sre","be","fs","de"], x:[], why:"Solid hands-on GCP operations exam.", uae:"Nearest GCP regions are Doha and Dammam — pick it if your employer is on GCP.", tags:[], cat:"Cloud", dom:["cloud"]},
{id:"adp", n:"Google Associate Data Practitioner", p:"Google Cloud", code:"ADP", usd:125, url:"https://cloud.google.com/learn/certification/data-practitioner", r:6, lv:[0,3], m:[], s:[], c:["de","ds"], x:[], why:"BigQuery, data prep and basic ML on GCP.", uae:"Moderate demand; BigQuery is common in startups and media.", tags:[], cat:"Data", dom:[]},
{id:"pca", n:"Google Professional Cloud Architect", p:"Google Cloud", code:"PCA", usd:200, url:"https://cloud.google.com/learn/certification/cloud-architect", r:8, lv:[3,6], m:[], s:[], c:["sa","ea","dev"], x:[], why:"Highly regarded case-study-based architecture exam.", uae:"Choose it when your clients are on GCP; otherwise AWS or Azure ranks higher here.", tags:[], cat:"Architecture", dom:["cloud"]},
{id:"pde", n:"Google Professional Data Engineer", p:"Google Cloud", code:"PDE", usd:200, url:"https://cloud.google.com/learn/certification/data-engineer", r:8, lv:[2,5], m:[], s:[], c:["de"], x:[], why:"Strong data-platform design exam centred on BigQuery and Dataflow.", uae:"Respected but less common than AWS/Azure data certs locally.", tags:[], cat:"Data", dom:[]},
{id:"pmle", n:"Google Professional Machine Learning Engineer", p:"Google Cloud", code:"PMLE", usd:200, url:"https://cloud.google.com/learn/certification/machine-learning-engineer", r:8, lv:[2,5], m:[], s:["ds"], c:["ai"], x:[], why:"Rigorous end-to-end ML exam: framing, Vertex AI, MLOps, GenAI.", uae:"Recognised across the region's ML teams.", tags:[], cat:"AI", dom:["ai"]},
{id:"pcde", n:"Google Professional Cloud DevOps Engineer", p:"Google Cloud", code:"PCDOE", usd:200, url:"https://cloud.google.com/learn/certification/cloud-devops-engineer", r:7, lv:[2,5], m:[], s:[], c:["sre","dev"], x:[], why:"The most SRE-flavoured cloud exam — SLOs, error budgets, incident response.", uae:"Great learning value even if your stack isn't GCP.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"gskill", n:"Google Cloud Skill Badges", p:"Google Cloud", code:"Skills Boost", usd:0, url:"https://www.cloudskillsboost.google/catalog", r:5, lv:[0,3], m:[], s:[], c:["fe","be","fs","dev","sre","de","ds","ai"], x:[], why:"Free lab-based badges; monthly no-cost credits often available.", uae:"Free way to try GCP before committing.", tags:["free"], cat:"Cloud", dom:["free"]},

/* ---------- Oracle ---------- */
{id:"ocif", n:"Oracle Cloud Infrastructure Foundations Associate", p:"Oracle", code:"1Z0-1085", usd:0, url:"https://mylearn.oracle.com/", r:5, lv:[0,2], m:[], s:[], c:["dba","be","fs","sa"], x:[], why:"Free OCI foundations exam and training on Oracle MyLearn (AI Foundations is free too).", uae:"Oracle runs Dubai and Abu Dhabi regions, including government cloud — strong in UAE public sector.", tags:["free"], cat:"Cloud", dom:["cloud","gov","free"]},
{id:"ociarch", n:"OCI Architect Associate", p:"Oracle", code:"1Z0-1072", usd:245, approx:true, url:"https://mylearn.oracle.com/", r:7, lv:[1,4], m:[], s:[], c:["sa","dba","dev"], x:[], why:"OCI networking, compute, storage and security design. Oracle frequently runs free-exam promotions.", uae:"Useful for UAE government and Oracle-heavy banks.", tags:[], cat:"Cloud", dom:["cloud","gov"]},
{id:"orjava", n:"Oracle Java SE 21 Developer Professional", p:"Oracle", code:"1Z0-830", usd:245, url:"https://education.oracle.com/", r:6, lv:[0,3], m:[], s:[], c:["be"], x:[], why:"Deep Java language exam. Helps in Java shops; unnecessary if you can show strong code.", uae:"Banks and telcos with Java estates value it.", tags:[], cat:"Dev & mobile", dom:["fin"]},
{id:"ordba", n:"Oracle Database Administration Professional", p:"Oracle", code:"OCP", usd:245, approx:true, url:"https://education.oracle.com/", r:7, lv:[1,5], m:[], s:["dba"], c:[], x:[], why:"Backup, recovery, performance and multitenant administration.", uae:"Oracle DB still runs core banking and government systems in the UAE.", tags:[], cat:"Data", dom:["gov","fin"]},

/* ---------- Anthropic ---------- */
{id:"ccarf", n:"Claude Certified Architect – Foundations", p:"Anthropic", code:"CCAR-F", usd:125, url:"https://anthropic-partners.skilljar.com/", r:7, lv:[2,5], m:[], s:["ai","sa"], c:["fs","be","em","cto"], x:[], why:"Agentic architecture, MCP, Claude Code and prompt/context design. Booked through the Claude Partner Network (free Registered tier); certificates belong to you, not your firm.", uae:"Launched March 2026 — an early-mover signal for UAE AI consultancies.", tags:["partner"], cat:"AI", dom:["ai"]},
{id:"ccdvf", n:"Claude Certified Developer – Foundations", p:"Anthropic", code:"CCDV-F", usd:125, url:"https://anthropic-partners.skilljar.com/", r:6, lv:[1,4], m:[], s:[], c:["ai","fs","be"], x:[], why:"Building with the Claude API, tool use and agent workflows.", uae:"Niche but growing with Claude adoption in the region.", tags:["partner","new"], cat:"AI", dom:["ai"]},
{id:"ccarp", n:"Claude Certified Architect – Professional", p:"Anthropic", code:"CCAR-P", usd:175, url:"https://anthropic-partners.skilljar.com/", r:7, lv:[3,6], m:[], s:[], c:["ai","sa","ea"], x:[], why:"Advanced multi-agent design, evaluation and production operations on Claude.", uae:"Pairs well with a hyperscaler AI exam for senior AI architects.", tags:["partner","new"], cat:"AI", dom:["ai"]},
{id:"anthacad", n:"Anthropic Academy courses", p:"Anthropic", code:"Free courses", usd:0, url:"https://anthropic.skilljar.com/", r:6, lv:[0,6], m:[], s:[], c:["ai","fs","be","fe","tpm","em"], x:[], why:"Free courses on the Claude API, MCP, Claude Code and AI fluency with completion certificates.", uae:"Zero-cost AI upskilling for whole teams.", tags:["free"], cat:"AI", dom:["ai","free"]},

/* ---------- Cloud native / platform ---------- */
{id:"kcna", n:"Kubernetes and Cloud Native Associate", p:"Linux Foundation", code:"KCNA", usd:250, url:"https://training.linuxfoundation.org/certification/kubernetes-cloud-native-associate/", r:5, lv:[0,2], m:[], s:[], c:["dev","sre"], x:[], why:"Multiple-choice cloud-native intro. Skip it if you can go straight to CKA.", uae:"Rarely asked for by name.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"cka", n:"Certified Kubernetes Administrator", p:"Linux Foundation", code:"CKA", usd:445, url:"https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/", r:9, lv:[1,5], m:["dev","sre"], s:["sa"], c:["be","fs","sec","ai"], x:[], why:"Hands-on, performance-based; the most respected Kubernetes credential. Price includes a free retake and two simulator sessions. Linux Foundation runs frequent 30–50% discounts.", uae:"Appears in most senior DevOps / platform job ads in Dubai.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"ckad", n:"Certified Kubernetes Application Developer", p:"Linux Foundation", code:"CKAD", usd:445, url:"https://training.linuxfoundation.org/certification/certified-kubernetes-application-developer-ckad/", r:7, lv:[1,4], m:[], s:[], c:["be","fs","dev"], x:[], why:"Hands-on deployment, configuration and debugging of apps on Kubernetes.", uae:"Good for backend engineers in platform-heavy companies.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"cks", n:"Certified Kubernetes Security Specialist", p:"Linux Foundation", code:"CKS", usd:445, url:"https://training.linuxfoundation.org/certification/certified-kubernetes-security-specialist/", r:8, lv:[2,5], m:[], s:["sec"], c:["sre","dev"], x:[], why:"Cluster hardening, supply chain and runtime security. Requires an active CKA.", uae:"Valued in regulated sectors running Kubernetes.", tags:[], cat:"Security", dom:["fin"]},
{id:"tf", n:"HashiCorp Terraform Associate", p:"HashiCorp", code:"004", usd:70.5, url:"https://developer.hashicorp.com/certifications/infrastructure-automation", r:8, lv:[1,4], m:[], s:["dev","sre"], c:["sa","be","fs","de"], x:[], why:"Cheap, fast and directly useful — infrastructure as code is in nearly every UAE DevOps job ad.", uae:"Best value-per-dirham certification on this page.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"rhcsa", n:"Red Hat Certified System Administrator", p:"Red Hat", code:"EX200", usd:500, approx:true, url:"https://www.redhat.com/en/services/training/ex200-red-hat-certified-system-administrator-rhcsa-exam", r:7, lv:[0,3], m:[], s:[], c:["dev","sre"], x:[], why:"Hands-on Linux administration. Price varies by country.", uae:"Respected in telco and government data centres.", tags:[], cat:"DevOps & platform", dom:["gov"]},
{id:"ccna", n:"Cisco Certified Network Associate", p:"Cisco", code:"200-301", usd:300, url:"https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html", r:6, lv:[0,3], m:[], s:[], c:["sre","dev","sec"], x:["fe","be","fs"], why:"Networking fundamentals. Valuable for infra roles; not relevant for application developers.", uae:"Still common in UAE enterprise IT and telcos.", tags:[], cat:"DevOps & platform", dom:[]},

/* ---------- Security ---------- */
{id:"isc2cc", n:"ISC2 Certified in Cybersecurity", p:"ISC2", code:"CC", usd:0, url:"https://www.isc2.org/certifications/cc", r:6, lv:[0,2], m:[], s:["sec"], c:["dev","sre","qa","be","fs"], x:[], why:"Free training and exam through ISC2's One Million CC programme ($50/yr maintenance after passing).", uae:"Free entry point recognised by UAE security teams.", tags:["free"], cat:"Security", dom:["free","gov"]},
{id:"secplus", n:"CompTIA Security+", p:"CompTIA", code:"SY0-701", usd:425, url:"https://www.comptia.org/certifications/security", r:7, lv:[0,3], m:[], s:["sec"], c:["dev","sre"], x:[], why:"Vendor-neutral security baseline. List price rose to about $425 in 2026; resellers discount it.", uae:"Common in government and defence-adjacent roles.", tags:[], cat:"Security", dom:["gov"]},
{id:"cissp", n:"CISSP", p:"ISC2", code:"CISSP", usd:749, url:"https://www.isc2.org/certifications/cissp", r:9, lv:[4,6], m:["sec"], s:["ea"], c:["sa","cto","em"], x:[], why:"Gold-standard security leadership credential; needs five years' experience (or become an Associate of ISC2 first). $135/yr maintenance.", uae:"Frequently mandatory for CISO and security-lead roles in UAE banks and government.", tags:[], cat:"Security", dom:["gov","fin"]},
{id:"ccsp", n:"CCSP", p:"ISC2", code:"CCSP", usd:599, url:"https://www.isc2.org/certifications/ccsp", r:8, lv:[3,6], m:[], s:["sec"], c:["sa","ea"], x:[], why:"Vendor-neutral cloud security architecture and operations.", uae:"Supports cloud adoption approvals in regulated UAE sectors.", tags:[], cat:"Security", dom:["cloud","fin"]},
{id:"cism", n:"CISM", p:"ISACA", code:"CISM", usd:760, sub:"$575 for ISACA members", url:"https://www.isaca.org/credentialing/cism", r:8, lv:[4,6], m:[], s:["sec","cto"], c:["ea","em"], x:[], why:"Security management, governance and risk programmes.", uae:"ISACA UAE chapter is active; widely requested for security managers.", tags:[], cat:"Security", dom:["gov","fin"]},
{id:"cisa", n:"CISA", p:"ISACA", code:"CISA", usd:760, sub:"$575 for ISACA members", url:"https://www.isaca.org/credentialing/cisa", r:8, lv:[3,6], m:[], s:[], c:["sec","ea"], x:[], why:"IT audit and assurance. Essential if you face regulator or internal audits regularly.", uae:"Core credential for CBUAE, DFSA and DESC audit work.", tags:[], cat:"Governance & privacy", dom:["fin","gov"]},
{id:"crisc", n:"CRISC", p:"ISACA", code:"CRISC", usd:760, sub:"$575 for ISACA members", url:"https://www.isaca.org/credentialing/crisc", r:7, lv:[3,6], m:[], s:[], c:["sec","ea","cto"], x:[], why:"IT risk identification, assessment and response.", uae:"Popular in UAE bank risk and compliance teams.", tags:[], cat:"Governance & privacy", dom:["fin"]},
{id:"ceh", n:"Certified Ethical Hacker", p:"EC-Council", code:"CEH", usd:1199, approx:true, url:"https://www.eccouncil.org/train-certify/certified-ethical-hacker-ceh/", r:5, lv:[0,3], m:[], s:[], c:["sec"], x:["dev","sre","be"], why:"Widely known in the Gulf, but mostly multiple-choice; OSCP is the stronger technical signal.", uae:"Sometimes named in government tenders — check before skipping.", tags:[], cat:"Security", dom:["gov"]},
{id:"oscp", n:"OffSec Certified Professional (PEN-200)", p:"OffSec", code:"OSCP+", usd:1749, url:"https://www.offsec.com/courses/pen-200/", r:9, lv:[1,5], m:[], s:["sec"], c:[], x:[], why:"Gruelling hands-on penetration-testing exam; price bundles 90 days of labs, course and one attempt.", uae:"Top technical signal for red-team and pentest roles in Dubai.", tags:[], cat:"Security", dom:[]},
{id:"gicsp", n:"Global Industrial Cyber Security Professional", p:"GIAC", code:"GICSP", usd:999, approx:true, url:"https://www.giac.org/certifications/global-industrial-cyber-security-professional-gicsp/", r:8, lv:[2,6], m:[], s:[], c:["sec"], x:[], why:"Bridges IT, engineering and OT security for industrial control systems.", uae:"Highly relevant to ADNOC, DEWA, ENEC and their suppliers.", tags:[], cat:"Security", dom:["energy"]},
{id:"isa62443", n:"ISA/IEC 62443 Cybersecurity Fundamentals Specialist", p:"ISA", code:"IC32 + exam", usd:1500, approx:true, sub:"course + exam", url:"https://www.isa.org/certification/certificate-programs/isa-iec-62443-cybersecurity-certificate-program", r:8, lv:[2,6], m:[], s:[], c:["sec","sa"], x:[], why:"The OT security standard most energy and utility operators reference.", uae:"Often a supplier requirement in UAE energy projects.", tags:["course"], cat:"Security", dom:["energy"]},

/* ---------- Governance, ISO & privacy ---------- */
{id:"iso27001", n:"ISO/IEC 27001 Lead Implementer or Lead Auditor", p:"PECB / CQI-IRCA", code:"ISO 27001:2022", usd:1500, approx:true, sub:"course + exam in Dubai", url:"https://pecb.com/en/education-and-certification-for-individuals/iso-iec-27001", r:8, lv:[2,6], m:[], s:["sec"], c:["ea","em","cto","sa","qa"], x:[], why:"Build or audit an information security management system. Typically a 5-day course with the exam included.", uae:"Maps directly to DESC ISR, UAE IA and ADHICS audits — the most UAE-relevant governance cert.", tags:["course"], cat:"Governance & privacy", dom:["gov","fin","health","energy"]},
{id:"iso42001", n:"ISO/IEC 42001 Lead Implementer", p:"PECB", code:"ISO 42001:2023", usd:1500, approx:true, sub:"course + exam", url:"https://pecb.com/en/education-and-certification-for-individuals/iso-iec-42001", r:7, lv:[3,6], m:[], s:[], c:["ai","ea","cto","tpm","em"], x:[], why:"AI management systems: risk, impact assessment and controls for responsible AI.", uae:"Rising fast with the UAE AI-agent mandate and the new federal AI authority.", tags:["course"], cat:"Governance & privacy", dom:["ai","gov"]},
{id:"iso22301", n:"ISO 22301 Lead Implementer", p:"PECB", code:"ISO 22301", usd:1500, approx:true, sub:"course + exam", url:"https://pecb.com/en/education-and-certification-for-individuals/iso-22301", r:6, lv:[3,6], m:[], s:[], c:["sre","ea","sec"], x:[], why:"Business continuity management systems.", uae:"Aligns with the UAE NCEMA 7000 business-continuity standard used by government and critical infrastructure.", tags:["course"], cat:"Governance & privacy", dom:["gov","energy"]},
{id:"cippe", n:"Certified Information Privacy Professional / Europe", p:"IAPP", code:"CIPP/E", usd:550, url:"https://iapp.org/certify/cippe/", r:7, lv:[2,6], m:[], s:[], c:["tpm","sec","ea","cto"], x:[], why:"GDPR law and practice.", uae:"UAE PDPL, DIFC and ADGM data laws are modelled on GDPR, so it transfers directly.", tags:[], cat:"Governance & privacy", dom:["privacy","health","fin"]},
{id:"cipm", n:"Certified Information Privacy Manager", p:"IAPP", code:"CIPM", usd:550, url:"https://iapp.org/certify/cipm/", r:6, lv:[3,6], m:[], s:[], c:["tpm","em","sec"], x:[], why:"Running a privacy programme: governance, DPIAs, metrics.", uae:"For DPO-track roles under PDPL and DIFC rules.", tags:[], cat:"Governance & privacy", dom:["privacy"]},
{id:"cdpse", n:"Certified Data Privacy Solutions Engineer", p:"ISACA", code:"CDPSE", usd:760, sub:"$575 for ISACA members", url:"https://www.isaca.org/credentialing/cdpse", r:7, lv:[2,5], m:[], s:[], c:["sec","be","de","sa","dba"], x:[], why:"Privacy engineering for builders — privacy by design, data lifecycle, architecture.", uae:"Helps engineers in health and finance meet PDPL and data-localisation rules.", tags:[], cat:"Governance & privacy", dom:["privacy","health"]},
{id:"aigp", n:"Artificial Intelligence Governance Professional", p:"IAPP", code:"AIGP", usd:649, approx:true, url:"https://iapp.org/certify/aigp/", r:7, lv:[3,6], m:[], s:[], c:["ai","tpm","ea","cto","em"], x:[], why:"AI governance, risk and regulation (EU AI Act, NIST AI RMF) for practitioners and leaders.", uae:"Valued by UAE entities building AI governance offices.", tags:[], cat:"Governance & privacy", dom:["ai","privacy"]},
{id:"itil", n:"ITIL 4 Foundation", p:"PeopleCert", code:"ITIL 4", usd:500, approx:true, url:"https://www.peoplecert.org/", r:6, lv:[1,5], m:[], s:[], c:["sre","em","tpm","ea"], x:[], why:"IT service management vocabulary: incidents, change, service value.", uae:"The ITSM language of UAE government and bank IT departments; often named in tenders.", tags:[], cat:"Product & delivery", dom:["gov","fin"]},

/* ---------- Data platforms ---------- */
{id:"dbde", n:"Databricks Certified Data Engineer Associate", p:"Databricks", code:"DEA", usd:200, url:"https://www.databricks.com/learn/certification/data-engineer-associate", r:8, lv:[1,4], m:[], s:["de"], c:["ds","ai"], x:[], why:"Lakehouse, Delta Lake, Spark SQL and pipelines.", uae:"Databricks is common in UAE banks, telcos and government data offices.", tags:[], cat:"Data", dom:[]},
{id:"dbgen", n:"Databricks Certified Generative AI Engineer Associate", p:"Databricks", code:"GenAI", usd:200, url:"https://www.databricks.com/learn/certification/genai-engineer-associate", r:7, lv:[2,4], m:[], s:[], c:["ai","de","ds"], x:[], why:"RAG, vector search and agent apps on the Databricks platform.", uae:"Useful where Databricks is the data platform.", tags:[], cat:"AI", dom:["ai"]},
{id:"dbfund", n:"Databricks Fundamentals accreditation", p:"Databricks", code:"Free", usd:0, url:"https://www.databricks.com/learn/training/home", r:5, lv:[0,2], m:[], s:[], c:["de","ds","dba"], x:[], why:"Free short accreditation through Databricks Academy.", uae:"Free first step before the paid associate exam.", tags:["free"], cat:"Data", dom:["free"]},
{id:"snow", n:"SnowPro Core", p:"Snowflake", code:"COF-C02", usd:175, url:"https://learn.snowflake.com/en/certifications/snowpro-core/", r:7, lv:[1,4], m:[], s:[], c:["de","dba","ds"], x:[], why:"Snowflake architecture, loading, performance and security.", uae:"Moderate local demand; strong with global firms in DIFC.", tags:[], cat:"Data", dom:[]},
{id:"mongo", n:"MongoDB Associate Developer", p:"MongoDB", code:"Associate", usd:150, url:"https://learn.mongodb.com/pages/certification-program", r:6, lv:[0,3], m:[], s:[], c:["be","fs","dba"], x:[], why:"CRUD, indexing, aggregation and data modelling with your language driver. Free learning paths on MongoDB University.", uae:"Common in startups and product companies.", tags:[], cat:"Data", dom:[]},
{id:"mongobadges", n:"MongoDB Skill Badges", p:"MongoDB", code:"Free · Credly", usd:0, url:"https://learn.mongodb.com/skills", r:5, lv:[0,4], m:[], s:[], c:["be","fs","dba","ai","de"], x:[], why:"Free short skill badges — e.g. building AI agents with MongoDB, data resilience, moving from SQL to the document model — verifiable on Credly.", uae:"Zero-cost proof of MongoDB and vector-search skills.", tags:["free"], cat:"Data", dom:["free"]},
{id:"dca", n:"Docker Certified Associate", p:"Mirantis", code:"DCA", usd:195, url:"https://training.mirantis.com/certification/dca-certification-exam/", r:5, lv:[0,3], m:[], s:[], c:["dev","sre","be","fs"], x:[], why:"Images, networking, storage and orchestration basics. Recognised, but CKA / CKAD now carry far more weight.", uae:"Rarely filtered on — Docker skills are assumed for most roles.", tags:[], cat:"DevOps & platform", dom:[]},
{id:"lil", n:"LinkedIn Learning certificates", p:"LinkedIn Learning", code:"Course certificates", usd:40, approx:true, sub:"per month (Premium)", url:"https://www.linkedin.com/learning/", r:4, lv:[0,2], m:[], s:[], c:["fe","be","fs","mn","mh","qa","dev","sre","de","ds","ai","tpm","dba","sec"], x:[], why:"Completion certificates, including vendor-branded Professional Certificates (Microsoft, Docker, Kong). Good learning evidence on your profile, but not proctored credentials.", uae:"Often free via employers or Dubai Culture's LinkedIn Learning licences; recruiters read them as learning, not certification.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"udemy", n:"Udemy course certificates", p:"Udemy", code:"Course certificates", usd:15, approx:true, sub:"per course on sale", url:"https://www.udemy.com/", r:3, lv:[0,1], m:[], s:[], c:["fe","be","fs","mn","mh","qa","dev","sre","de","ds","ai","tpm","dba","sec"], x:[], why:"Cheap, practical courses — great for learning or exam prep, near-zero signal as a credential. Use them to prepare for a real exam.", uae:"Not filtered on by UAE employers.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"neo4j", n:"Neo4j Certified Professional", p:"Neo4j", code:"Free", usd:0, url:"https://graphacademy.neo4j.com/certifications/neo4j-certification/", r:5, lv:[0,4], m:[], s:[], c:["be","de","ai","dba"], x:[], why:"Free graph-database certification; handy for GraphRAG work.", uae:"Niche, but costs nothing.", tags:["free"], cat:"Data", dom:["free"]},
{id:"dbt", n:"dbt Analytics Engineering", p:"dbt Labs", code:"Analytics Eng.", usd:200, url:"https://www.getdbt.com/certifications", r:6, lv:[1,4], m:[], s:[], c:["de"], x:[], why:"Modelling, testing and documenting transformations with dbt.", uae:"Growing with modern data stacks in fintech.", tags:[], cat:"Data", dom:[]},
{id:"kafka", n:"Confluent Certified Developer for Apache Kafka", p:"Confluent", code:"CCDAK", usd:150, url:"https://www.confluent.io/certification/", r:7, lv:[2,5], m:[], s:[], c:["be","de","sa"], x:[], why:"Producers, consumers, streams and schema registry.", uae:"Event-driven core banking and payments projects use Kafka heavily.", tags:[], cat:"Data", dom:["fin"]},
{id:"tfdev", n:"TensorFlow Developer Certificate", p:"Google", code:"Discontinued", usd:null, note:"Discontinued", url:"https://www.tensorflow.org/", r:1, lv:[0,6], m:[], s:[], c:[], x:["ds","ai"], why:"Discontinued — ignore older blog posts recommending it.", uae:"Not available.", tags:["retired"], cat:"AI", dom:[]},

/* ---------- AI learning ---------- */
{id:"nvgen", n:"NVIDIA-Certified Associate: Generative AI LLMs", p:"NVIDIA", code:"NCA-GENL", usd:125, url:"https://www.nvidia.com/en-us/learn/certification/generative-ai-llm-associate/", r:6, lv:[1,4], m:[], s:[], c:["ai","ds"], x:[], why:"LLM fundamentals, prompting, fine-tuning and NVIDIA tooling.", uae:"Relevant as UAE builds GPU-heavy national AI infrastructure.", tags:[], cat:"AI", dom:["ai"]},
{id:"hf", n:"Hugging Face courses (LLM, Agents, MCP)", p:"Hugging Face", code:"Free", usd:0, url:"https://huggingface.co/learn", r:7, lv:[0,4], m:[], s:[], c:["ai","ds"], x:[], why:"Free, deeply practical courses with completion certificates.", uae:"Builds the portfolio that UAE AI teams actually look at.", tags:["free"], cat:"AI", dom:["ai","free"]},
{id:"dlai", n:"DeepLearning.AI short courses", p:"DeepLearning.AI", code:"Free", usd:0, url:"https://www.deeplearning.ai/short-courses/", r:7, lv:[0,6], m:[], s:[], c:["ai","ds","fs","be","tpm"], x:[], why:"Free one-to-two-hour courses on agents, RAG, evals and MCP, built with the vendors.", uae:"Fastest free way to stay current.", tags:["free"], cat:"AI", dom:["ai","free"]},
{id:"kaggle", n:"Kaggle Learn certificates", p:"Kaggle", code:"Free", usd:0, url:"https://www.kaggle.com/learn", r:5, lv:[0,2], m:[], s:[], c:["ds","de","ai"], x:[], why:"Free micro-courses in Python, pandas, ML and SQL.", uae:"Good for freshers; pair with competition work.", tags:["free"], cat:"AI", dom:["free"]},
{id:"prompters", n:"One Million Prompters", p:"Dubai Centre for AI", code:"Free", usd:0, url:"https://gulfnews.com/ask-gulf-news/ask-gulf-news-free-dubai-government-courses-to-help-you-build-job-skills-1.500593095", r:4, lv:[0,6], m:[], s:[], c:["tpm","qa","fe","em"], x:[], why:"Dubai government's free AI prompt-literacy programme: four one-hour online modules and a certificate.", uae:"Local, free and recognisable to Dubai government employers.", tags:["free","uae"], cat:"AI", dom:["ai","free"]},
{id:"arabcoders", n:"One Million Arab Coders", p:"Dubai Future Foundation", code:"Free", usd:0, url:"https://www.arabcoders.ae/", r:4, lv:[0,0], m:[], s:[], c:["fe","be","fs","mn","mh"], x:[], why:"Free beginner coding programme for Arabic-speaking learners.", uae:"UAE-government backed starting point for career changers.", tags:["free","uae"], cat:"Dev & mobile", dom:["free"]},
{id:"awssb", n:"AWS Skill Builder (free tier)", p:"AWS", code:"Free", usd:0, url:"https://skillbuilder.aws/", r:6, lv:[0,3], m:[], s:[], c:["fe","be","fs","dev","sre","de","ds","ai","tpm"], x:[], why:"Free official prep courses and practice questions for every AWS exam.", uae:"Use before paying for third-party bootcamps.", tags:["free"], cat:"Cloud", dom:["free"]},

/* ---------- QA ---------- */
{id:"ctfl", n:"ISTQB Certified Tester Foundation Level", p:"ISTQB", code:"CTFL v4.0", usd:250, approx:true, url:"https://www.istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/", r:8, lv:[0,3], m:["qa"], s:[], c:["tpm"], x:[], why:"The global QA vocabulary and baseline. Fee varies by exam provider.", uae:"UAE government and bank tenders often ask for ISTQB-certified testers.", tags:[], cat:"QA", dom:["gov"]},
{id:"ctaltae", n:"ISTQB Advanced Test Automation Engineering", p:"ISTQB", code:"CTAL-TAE", usd:300, approx:true, url:"https://www.istqb.org/certifications/", r:7, lv:[2,5], m:[], s:["qa"], c:[], x:[], why:"Automation architecture, frameworks and CI integration.", uae:"Signals seniority for automation leads.", tags:[], cat:"QA", dom:[]},
{id:"ctai", n:"ISTQB Certified Tester AI Testing", p:"ISTQB", code:"CT-AI", usd:250, approx:true, url:"https://www.istqb.org/certifications/", r:6, lv:[2,5], m:[], s:[], c:["qa","ai"], x:[], why:"Testing AI-based systems and using AI in testing.", uae:"Timely as UAE entities ship AI agents into production.", tags:[], cat:"QA", dom:["ai"]},

/* ---------- Product, delivery & architecture ---------- */
{id:"pmp", n:"Project Management Professional", p:"PMI", code:"PMP", usd:575, sub:"$405 for PMI members", url:"https://www.pmi.org/certifications/project-management-pmp", r:8, lv:[3,6], m:[], s:["tpm","em"], c:["ea","cto","sa"], x:[], why:"Predictive, agile and hybrid delivery. Needs 35 hours of training and 3–5 years leading projects.", uae:"Strongly valued in UAE government and semi-government programmes.", tags:[], cat:"Product & delivery", dom:["gov"]},
{id:"psm", n:"Professional Scrum Master I", p:"Scrum.org", code:"PSM I", usd:200, url:"https://www.scrum.org/assessments/professional-scrum-master-i-certification", r:7, lv:[1,4], m:[], s:["em"], c:["tpm","qa"], x:[], why:"No mandatory course and no renewal fee — cheaper and more rigorous than CSM.", uae:"Widely recognised by UAE agile teams.", tags:[], cat:"Product & delivery", dom:[]},
{id:"pspo", n:"Professional Scrum Product Owner I", p:"Scrum.org", code:"PSPO I", usd:200, url:"https://www.scrum.org/assessments/professional-scrum-product-owner-i-certification", r:7, lv:[1,4], m:[], s:["tpm"], c:["em"], x:[], why:"Product ownership, backlog and value — lifetime certification.", uae:"Common requirement for product owner roles in banks.", tags:[], cat:"Product & delivery", dom:[]},
{id:"csm", n:"Certified ScrumMaster", p:"Scrum Alliance", code:"CSM", usd:600, approx:true, sub:"includes mandatory course", url:"https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster", r:5, lv:[0,3], m:[], s:[], c:["tpm","em"], x:[], why:"Course-based and well known, but renews every two years. PSM I is usually better value.", uae:"Recognised; often employer-funded.", tags:["course"], cat:"Product & delivery", dom:[]},
{id:"safepopm", n:"SAFe Product Owner / Product Manager", p:"Scaled Agile", code:"POPM", usd:800, approx:true, sub:"includes mandatory course", url:"https://scaledagile.com/training/safe-product-owner-product-manager/", r:6, lv:[2,5], m:[], s:[], c:["tpm"], x:[], why:"Product roles inside SAFe release trains.", uae:"UAE banks and telcos running SAFe ask for it.", tags:["course"], cat:"Product & delivery", dom:["fin"]},
{id:"togaf", n:"TOGAF Enterprise Architecture Foundation + Practitioner", p:"The Open Group", code:"OGEA-103", usd:610, url:"https://www.opengroup.org/certifications", r:8, lv:[4,6], m:["ea"], s:["sa","cto"], c:["em"], x:[], why:"Combined exam saves $200 vs taking Foundation ($405) and Practitioner ($405) separately.", uae:"Default EA framework in UAE government transformation programmes.", tags:[], cat:"Architecture", dom:["gov","fin"]},

/* ---------- Dev & mobile ---------- */
{id:"metafe", n:"Meta Front-End Developer Professional Certificate", p:"Meta · Coursera", code:"Coursera", usd:49, sub:"per month subscription", url:"https://www.coursera.org/professional-certificates/meta-front-end-developer", r:5, lv:[0,1], m:[], s:[], c:["fe"], x:[], why:"Structured beginner path. The portfolio you build matters more than the badge.", uae:"Fine for freshers; ignored for experienced hires.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"fcc", n:"freeCodeCamp certifications", p:"freeCodeCamp", code:"Free", usd:0, url:"https://www.freecodecamp.org/learn", r:6, lv:[0,1], m:[], s:[], c:["fe","fs","be"], x:[], why:"Free, project-based web development certifications.", uae:"Good for freshers and career changers.", tags:["free"], cat:"Dev & mobile", dom:["free"]},
{id:"w3s", n:"W3Schools certificates", p:"W3Schools", code:"Paid", usd:95, approx:true, url:"https://campus.w3schools.com/", r:2, lv:[0,6], m:[], s:[], c:[], x:["fe","be","fs"], why:"Low hiring signal — spend the money on hosting a real project.", uae:"Not filtered on by UAE employers.", tags:[], cat:"Dev & mobile", dom:[]},
{id:"cpacc", n:"IAAP Certified Professional in Accessibility Core Competencies", p:"IAAP", code:"CPACC", usd:485, sub:"$385 for IAAP members", url:"https://www.accessibilityassociation.org/certification", r:6, lv:[1,5], m:[], s:[], c:["fe","qa","mh","mn","tpm"], x:[], why:"Accessibility principles, standards and disability awareness.", uae:"Accessibility for People of Determination is a priority in UAE government digital services.", tags:[], cat:"Dev & mobile", dom:["gov"]},
{id:"metaand", n:"Meta Android Developer Professional Certificate", p:"Meta · Coursera", code:"Coursera", usd:49, sub:"per month subscription", url:"https://www.coursera.org/professional-certificates/meta-android-developer", r:5, lv:[0,1], m:[], s:[], c:["mn"], x:[], why:"Kotlin and Android basics for beginners.", uae:"Only useful before you have published apps.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"metaios", n:"Meta iOS Developer Professional Certificate", p:"Meta · Coursera", code:"Coursera", usd:49, sub:"per month subscription", url:"https://www.coursera.org/professional-certificates/meta-ios-developer", r:5, lv:[0,1], m:[], s:[], c:["mn"], x:[], why:"Swift and SwiftUI basics for beginners.", uae:"Only useful before you have published apps.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"metarn", n:"Meta React Native Specialization", p:"Meta · Coursera", code:"Coursera", usd:49, sub:"per month subscription", url:"https://www.coursera.org/specializations/meta-react-native", r:5, lv:[0,1], m:[], s:[], c:["mh"], x:[], why:"Structured React Native intro.", uae:"Portfolio apps carry far more weight.", tags:["course"], cat:"Dev & mobile", dom:[]},
{id:"aad", n:"Google Associate Android Developer", p:"Google", code:"Retired", usd:null, note:"Retired", url:"https://developer.android.com/", r:1, lv:[0,6], m:[], s:[], c:[], x:["mn","mh"], why:"Retired by Google — no official Android certification exists now.", uae:"Not available.", tags:["retired"], cat:"Dev & mobile", dom:[]},
{id:"swiftcu", n:"App Development with Swift Certified User", p:"Apple · Certiport", code:"Certiport", usd:100, approx:true, url:"https://certiport.pearsonvue.com/Certifications/Apple/App-Development-with-Swift/Overview", r:3, lv:[0,1], m:[], s:[], c:[], x:["mn"], why:"Aimed at students; professional iOS hiring ignores it.", uae:"No local demand.", tags:[], cat:"Dev & mobile", dom:[]},
{id:"pcap", n:"Python Institute PCAP", p:"Python Institute", code:"PCAP-31-03", usd:295, url:"https://pythoninstitute.org/pcap", r:5, lv:[0,2], m:[], s:[], c:["be","ds","qa"], x:[], why:"Certified Associate Python Programmer. Some value for freshers; code samples matter more.", uae:"Occasionally requested by training-led employers.", tags:[], cat:"Dev & mobile", dom:[]},

/* ---------- Healthcare ---------- */
{id:"fhir", n:"HL7 FHIR Proficiency", p:"HL7 International", code:"FHIR R4", usd:250, approx:true, url:"https://www.hl7.org/certification/", r:7, lv:[1,5], m:[], s:[], c:["be","fs","sa","de"], x:[], why:"FHIR resources, REST APIs, profiles and implementation guides.", uae:"Dubai's NABIDH and Abu Dhabi's Malaffi health-information exchanges are HL7 / FHIR based.", tags:[], cat:"Governance & privacy", dom:["health"]}
];

var TIER = [
  {key:"must", label:"Must", desc:"Do these — they directly unlock interviews and promotions.", bg:"#0B5A53", fg:"#FFFFFF", empty:"Nothing is truly mandatory for this combination — that's the honest answer. Start with the Should list."},
  {key:"should", label:"Should", desc:"High return once the musts are done.", bg:"#24567F", fg:"#FFFFFF", empty:"No strong second-tier picks here; invest in projects instead."},
  {key:"could", label:"Could", desc:"Situational — take if your employer, client or sector uses it.", bg:"#F1DDB0", fg:"#4E3300", empty:"No situational picks."},
  {key:"skip", label:"Don't need", desc:"Outgrown, retired, or low signal for this path.", bg:"#DDE2E0", fg:"#2E3735", empty:"Nothing to avoid for this combination."}
];

function aedOf(c){ if (c.aed) return c.aed; if (c.usd == null) return null; return Math.round(c.usd * PEG); }
function fmt(n){ return n.toLocaleString("en-US"); }
function costLabel(c, cur){
  if (c.usd == null) return c.note || "—";
  if (c.usd === 0) return "Free";
  var pre = c.approx ? "~" : "";
  if (cur === "AED") return pre + "AED " + fmt(aedOf(c));
  return pre + "$" + (c.usd % 1 ? c.usd.toFixed(2) : fmt(c.usd));
}
function subLabel(c, cur){
  if (!c.sub) return "";
  if (cur !== "AED") return c.sub;
  return c.sub.replace(/\$(\d[\d,]*)/g, function(m, n){ return "AED " + fmt(Math.round(parseFloat(n.replace(/,/g, "")) * PEG)); });
}
function holdStyle(on){
  return "min-height:44px; padding:0 12px; border-radius:8px; cursor:pointer; font-size:13px; font-weight:600; white-space:nowrap; " +
    (on ? "background:#DCEFE8; color:#0B4A44; border:1px solid #0B5A53" : "background:#FFFFFF; color:#14201F; border:1px solid #A8B5B1");
}
var BADGE_COLORS = ["#E0A033", "#7CC4B6", "#9DBCE0"];
var BADGE_POS = [[-16, 0], [-22, 22], [-16, 44]];
function badgeStyle(i){
  return "position:absolute; z-index:2; pointer-events:none; width:26px; height:26px; border-radius:50%; border:2px solid #FFFFFF; display:flex; align-items:center; justify-content:center; color:#102A28; box-shadow:0 2px 6px rgba(16,42,40,.25); left:" + BADGE_POS[i][0] + "px; top:" + BADGE_POS[i][1] + "px; background:" + BADGE_COLORS[i];
}
function moneyStyle(on){
  return "min-height:40px; min-width:52px; padding:0 12px; border:0; border-radius:999px; cursor:pointer; font: 600 13px 'IBM Plex Mono', monospace; " +
    (on ? "background:#102A28; color:#FFFFFF" : "background:transparent; color:#3F4A47");
}
function barColor(r){ return r >= 8 ? "#0B5A53" : (r >= 6 ? "#24567F" : "#A86E10"); }
var TAGSTY = {
  free:["Free","#DCEFE8","#0B4A44"], "new":["New 2026","#E1E9F4","#1D466B"], retired:["Retired","#F4DEDA","#7A2418"], retiring:["Retiring","#F4DEDA","#7A2418"],
  partner:["Partner Network","#EEE6F5","#4B2A68"], course:["Course-based","#ECEEED","#38423F"], uae:["UAE programme","#F6EBD3","#6E4700"]
};
function roleLabel(k){ for (var i=0;i<ROLES.length;i++){ if (ROLES[i].k===k) return ROLES[i].label; } return k; }
function shortRoles(list){ return list.map(function(k){ return roleLabel(k).split(" (")[0].split(" /")[0]; }).join(", "); }

function baseTier(c, role){
  if (c.m.indexOf(role) > -1) return 3;
  if (c.s.indexOf(role) > -1) return 2;
  if (c.c.indexOf(role) > -1) return 1;
  if (c.x.indexOf(role) > -1) return 0;
  return -1;
}
function tierFor(c, role, lv){
  var b = baseTier(c, role);
  if (b <= 0) return {t:b, note:""};
  if (lv > c.lv[1]) return {t:0, note:"Outgrown at " + LEVELS[lv].name + " level"};
  if (lv < c.lv[0]) return {t:Math.max(1, b - 1), note:"Aim for this at " + LEVELS[c.lv[0]].name + " level"};
  return {t:b, note:""};
}

function decorate(c, extra, cur, held){
  var tags = (c.tags || []).map(function(t){ var s = TAGSTY[t] || [t,"#ECEEED","#38423F"]; return {t:s[0], style:"font: 600 11px/1 'IBM Plex Mono', monospace; padding: 5px 8px; border-radius: 4px; background:" + s[1] + "; color:" + s[2]}; });
  var roles = [];
  if (c.m.length) roles.push("Must for " + shortRoles(c.m));
  if (c.s.length) roles.push("Should for " + shortRoles(c.s));
  return {
    n:c.n, p:c.p, code:c.code, url:c.url, why:c.why, uae:c.uae,
    costLabel:costLabel(c, cur), sub:subLabel(c, cur), hasSub:!!c.sub,
    id:c.id, held:!!held, holdLabel: held ? "✓ Earned" : "+ I have this", holdStyle:holdStyle(!!held),
    rText:c.r + "/10",
    barStyle:"height:100%; border-radius:3px; width:" + (c.r * 10) + "%; background:" + barColor(c.r),
    tags:tags,
    note:(extra && extra.note) || "", hasNote:!!(extra && extra.note),
    rolesText: roles.length ? roles.join(" · ") : "Situational for most roles",
    cardStyle:"background:" + (held ? "#EEF6F3" : "#FFFFFF") + "; border:1px solid " + (held ? "#7FB5AC" : "#D5DCD9") + "; border-radius:12px; padding:16px; display:flex; flex-direction:column; gap:10px; min-width:0; overflow-wrap:break-word" + ((extra && extra.accent) ? "; border-top:4px solid " + extra.accent : "")
  };
}

function btnStyle(on, kind){
  var accent = kind === "tgt" ? "#8A5A00" : "#0B5A53";
  return "width:100%; min-width:0; min-height:44px; padding:6px 12px; display:inline-flex; flex-direction:column; align-items:flex-start; justify-content:center; gap:1px; border-radius:8px; cursor:pointer; font-size:14px; line-height:1.2; text-align:left; " +
    (on ? "background:" + accent + "; color:#FFFFFF; border:1px solid " + accent : "background:#FFFFFF; color:#14201F; border:1px solid #A8B5B1");
}
function chipStyle(on){
  return "min-height:44px; padding:0 14px; border-radius:999px; cursor:pointer; font-size:14px; font-weight:500; white-space:nowrap; flex-shrink:0; " +
    (on ? "background:#102A28; color:#FFFFFF; border:1px solid #102A28" : "background:#FFFFFF; color:#14201F; border:1px solid #A8B5B1");
}
function byRating(a, b){ return (b.r - a.r) || ((a.usd || 0) - (b.usd || 0)); }
